flathub_packages_present:
  - name: com.google.Chrome
  - name: org.mozilla.firefox
  - name: org.mozilla.Thunderbird
  - name: org.libreoffice.LibreOffice
  - name: org.gimp.GIMP # pixel design
  - name: org.inkscape.Inkscape # vector design
  - name: org.geany.Geany # basic ide / texeditor
  - name: org.gnome.TextEditor # basic texeditor
  - name: io.github.wereturtle.ghostwriter # markdown editor
  - name: org.remmina.Remmina # rdp client
  - name: com.github.tchx84.Flatseal # flatpak permissions manager
  - name: ca.desrt.dconf-editor # gnome config editor

apt_packages_present:
  - name: flatpak
  - name: gnome-software-plugin-flatpak
  - name: python-is-python3
  - name: python3-psutil
  - name: gnupg
  - name: software-properties-common
  - name: libcanberra-gtk-module
  - name: rsync
  - name: curl
  - name: shutter
  - name: gnome-shell-extension-manager

  - name: task
    deb_path: https://github.com/go-task/task/releases/latest/download/task_linux_amd64.deb

  - name: seafile-gui
    key: https://linux-clients.seafile.com/seafile.asc
    repo_url: deb [arch=amd64 signed-by=/etc/apt/keyrings/seafile] https://linux-clients.seafile.com/seafile-deb/{{ ansible_distribution_release }}/ stable main
    repo_filename: seafile
  - name: code
    key: https://packages.microsoft.com/keys/microsoft.asc
    repo_url: deb [arch=amd64,arm64,armhf signed-by=/etc/apt/keyrings/vscode] https://packages.microsoft.com/repos/code stable main
    repo_filename: vscode
  - name: terraform
    key: https://apt.releases.hashicorp.com/gpg
    repo_url: deb [signed-by=/etc/apt/keyrings/hashicorp] https://apt.releases.hashicorp.com {{ ansible_distribution_release }} main
    repo_filename: hashicorp
  - name: teamviewer
    key: https://linux.teamviewer.com/pubkey/currentkey.asc
    repo_url: deb [signed-by=/etc/apt/keyrings/teamviewer] https://linux.teamviewer.com/deb stable main
    repo_filename: teamviewer

binaries_present:
  # only files and folders in the include list will be unarchived, archive file will be deleted
  - name: hcloud
    url: https://github.com/hetznercloud/cli/releases/latest/download/hcloud-linux-amd64.tar.gz
    location: /usr/local/bin/
    include: [hcloud]
    archive: true

    # to install this package: $ sudo ./usr/local/bin/<actual-vmware-binary>
    # could be automated via register results - get binary name / call with "--deferred-gtk" option
  - name: vmware-workstation
    url: https://www.vmware.com/go/getworkstation-linux
    location: /usr/local/bin/
    archive: false

apt_packages_absent:
  - name: libreoffice-common
  - name: libreoffice-core
  - name: libreoffice-gnome
  - name: libreoffice-gtk3
  - name: libreoffice-help-common
  - name: libreoffice-help-en-us
  - name: libreoffice-style-colibre
  - name: libreoffice-style-elemtary

  - name: evolution
  - name: evolution-exchange
  - name: evolution-plugins
  - name: evolution-common
  - name: evolution-webcal

  - name: firefox-esr
  - name: gnome-text-editor
  - name: gedit
  - name: yelp

  - name: gnome-games
  - name: transmission-gtk
  - name: gnome-maps
  - name: malcontent
  - name: gnome-chess
  - name: aisleriot
  - name: gnome-nibbles
  - name: iagno
  - name: lightsoff
  - name: four-in-a-row
  - name: gnome-robots
  - name: pegsolitaire
  - name: gnome-2048
  - name: hitori
  - name: gnome-klotski
  - name: gnome-mines
  - name: gnome-mahjongg
  - name: gnome-sudoku
  - name: quadrapassel
  - name: swell-foop
  - name: gnome-tetravex
  - name: gnome-taquin
  - name: five-or-more
  - name: tali
